version: "3.3"
services:
  sonarqube:
    container_name: sonarqube_74
    image: sonarqube:7.4-community
    restart: always
    expose:
      - 9000
    ports:
      - 9000:9000   # web-ui (http)
    networks:
      - sonarnet
    environment:
      - sonar.jdbc.url=jdbc:postgresql://postgres-prod.saude-go.net:5444/sonar74
      - sonar.jdbc.username=sonaqube
      - sonar.jdbc.password=s0n4rqub3@@2274
      - TZ=America/Sao_Paulo  
    volumes:
      - $HOME/sonar/conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
      - $HOME/sonar/certs:/etc/ssl/certs
      - /etc/ssl/certs/java/cacerts:/etc/ssl/certs/java/cacerts  

  reverse_proxy:
    container_name: reverse_proxy
    depends_on:
      - sonarqube
    image: nginx
    networks:
      - sonarnet
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - $HOME/sonar/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - $HOME/sonar/certs:/etc/ssl/certs
      - /etc/ssl/certs/java/cacerts:/etc/ssl/certs/java/cacerts  

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:

networks:
  sonarnet:
    driver: bridge
